apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: ephemeral-pr-envs
  namespace: argocd

spec:

  # Delete apps (and their namespace) when PR is closed/merged
  syncPolicy:
    preserveResourcesOnDeletion: false

  generators:
  - pullRequest:
      github:
        owner: MdMaaz2003
        repo: ephemeral-demo

        tokenRef:
          secretName: github-token
          key: token

      requeueAfterSeconds: 30

  template:

    metadata:
      name: pr-{{number}}

    spec:

      project: default

      source:
        repoURL: https://github.com/MdMaaz2003/ephemeral-demo.git
        targetRevision: "{{head_sha}}"
        path: helm/my-app

        helm:
          valueFiles:
          - values.yaml
          - values-ephemeral.yaml

          parameters:
          - name: ingress.host
            value: pr-{{number}}.127.0.0.1.sslip.io

      destination:
        server: https://kubernetes.default.svc
        namespace: pr-{{number}}

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
        - CreateNamespace=true

        managedNamespaceMetadata:
          labels:
            managed-by: argocd-ephemeral