replicaCount: 2

image:
  repository: nginx
  tag: latest

service:
  port: 80

ingress:
  host: my-app.local

serviceAccount:
  create: false
  automount: false
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

  
